- name: update ubuntu
  when: ansible_distribution == 'Ubuntu'
  shell: |
    apt-get update

- name: update CentOS
  when: ansible_distribution == 'CentOS'
  shell: |
    yum -y update

- name: Update repositories cache
  yum:
    name: '*'
    state: latest
  register: yum_update_result
  changed_when: yum_update_result | changed

- name: install Nginx
  apt:
    name: nginx
    state: present
  notify:
    - Restart Nginx
