- name: update ubuntu
  when: ansible_distribution == 'Ubuntu'
  shell: |
    apt-get update

- name: update CentOS
  when: ansible_distribution == 'CentOS'
  shell: |
    yum -y update



- name: install Nginx
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: nginx
    state: present
  notify:
    - Restart Nginx

- name: install Nginx
  when: ansible_distribution == 'CentOS'
  yum:
    name: nginx
    state: present
  notify:
    - Restart Nginx
